version: '2'

services:
    web:
        image: nginx:latest
        volumes:
            - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        ports:
            - "8080:80"
        networks:
            - local

    php:
        build: docker/php/
        volumes:
            - .:/var/www/html
        networks:
            - local

    database:
        image: mariadb:10.3
        volumes:
            - database:/var/lib/mysql
        ports:
            - "3307:3306"
        env_file:
            - ./docker/mysql/.env
        networks:
            - local

volumes:
    database: ~

networks:
    local: ~
